---
title: "Biblioteca Setorial - Departamento de Fitopatologia - UFV"
output: 
  flexdashboard::flex_dashboard:
    theme: flatly
    logo: icon-bbt3.png
    css: style.css
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readxl)
library(tidyverse)
library(crosstalk)
library(plotly)
library(viridis)
library(DT)
Sys.setlocale("LC_ALL", 'pt_BR.UTF-8')
bbt <- read_excel("acervo-bbt-dfp.xlsx")
bbt <- select(bbt, -1)
bbt <- arrange(bbt, codigo)
```




Column {data-width=250}
-----------------------------------------------------------------------

### Apresentação 

Bem-vindo à página de consulta aos **livros** do acervo da **Biblioteca Setorial** do Departamento de Fitopatologia da Universidade Federal de Viçosa. A tabela está ordenada pelo número de catalogação do livro. Clique no nome de qualquer coluna para alterar a ordenação. Entre qualquer termo no campo de busca para consultar. Use "backspace" para limpar a busca e realizar nova consulta. 
 
 
<h2> Procedimentos para empréstimos </h2>

- O material deve ser solicitado aos assistentes nos horários afixados na porta do recinto, atualizados a cada semestre. 

-	No primeiro empréstimo, será criada uma ficha cadastral onde serão registrados os empréstimos

-	O empréstimo é feito por at'é 15 dias consecutivos, podendo ser renovado por mesmo período, caso não esteja na lista de espera. 

-	Não é permitido o empréstimo de revistas mas os exemplares podem ser retirados para fazer fotocópia e devolvidos dentro de uma hora. 

-	Aqueles que por algum motivo perderem ou danificarem o exemplar, deverão assumir o ônus de ressarcir o valor do mesmo.

-	O "nada consta" relativos aos empréstimos deverá ser solicitado aos bolsistas e levado para assinatura do professor responsável pela biblioteca setorial, Prof. Gleiber Quintão Furtado (gfurtado@ufv.br - 38991108)

Número de livros: `r nrow(bbt)`<br>
Última atualização: `r format(Sys.Date(), "%d %b %Y")`



### Número de livros por ano de publicação {data-height=230}

```{r}
bbt %>% 
  plot_ly(x = ~ano, color = I("mediumaquamarine")) %>% 
  layout(barmode = 'stack',
                 margin=list(l=60,r=30,t=40,b=40))

```



Column {}
-----------------------------------------------------------------------

### Tabela de livros do acervo


```{r}
datatable(bbt, 
          extensions = c('Buttons', 'ColReorder'),
          escape = TRUE,
          rownames = FALSE, 
          colnames = c('Num. de catalogação', 'Título', 'Autor', 'Volume', 'Ano', 'N. de exemplares', 'Edição'), 
         class = 'cell-border stripe',
                      options=list(dom = 'Bfrtip',
                                   buttons = c( 'excel', 'pdf'), deferRender=TRUE, 
                          scrollY=500, 
                          scroller=TRUE,
                          colReorder = F,
                         
  pageLength = 100,
    fontSize = 8,
  lengthMenu = c(100, 250, 500))) %>% 
 formatStyle(
  c('codigo', 'titulo', 'autor', 'volume', 'ano', 'qtdade', 'edicao'),
  fontSize = '100%')
```


